// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DECOMPILE_GHIDRA_IPC_H_
#define FLATBUFFERS_GENERATED_DECOMPILE_GHIDRA_IPC_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ghidra {
namespace ipc {

struct DataType;
struct DataTypeBuilder;

struct Storage;
struct StorageBuilder;

struct Varnode;
struct VarnodeBuilder;

struct HighSymbol;
struct HighSymbolBuilder;

struct HighFunction;
struct HighFunctionBuilder;

struct PcodeOp;
struct PcodeOpBuilder;

struct Diagnostic;
struct DiagnosticBuilder;

struct RegisterProgramRequest;
struct RegisterProgramRequestBuilder;

struct RegisterProgramResponse;
struct RegisterProgramResponseBuilder;

struct DeregisterProgramRequest;
struct DeregisterProgramRequestBuilder;

struct DeregisterProgramResponse;
struct DeregisterProgramResponseBuilder;

struct FlushNativeRequest;
struct FlushNativeRequestBuilder;

struct FlushNativeResponse;
struct FlushNativeResponseBuilder;

struct DecompileFunctionRequest;
struct DecompileFunctionRequestBuilder;

struct DecompileFunctionResponse;
struct DecompileFunctionResponseBuilder;

struct StructureGraphRequest;
struct StructureGraphRequestBuilder;

struct StructureGraphResponse;
struct StructureGraphResponseBuilder;

struct SetActionRequest;
struct SetActionRequestBuilder;

struct SetActionResponse;
struct SetActionResponseBuilder;

struct SetOptionsRequest;
struct SetOptionsRequestBuilder;

struct SetOptionsResponse;
struct SetOptionsResponseBuilder;

enum ResponseStatus : int8_t {
  ResponseStatus_OK = 0,
  ResponseStatus_TIMEOUT = 1,
  ResponseStatus_ANALYSIS_FAILED = 2,
  ResponseStatus_PARTIAL = 3,
  ResponseStatus_MIN = ResponseStatus_OK,
  ResponseStatus_MAX = ResponseStatus_PARTIAL
};

inline const ResponseStatus (&EnumValuesResponseStatus())[4] {
  static const ResponseStatus values[] = {
    ResponseStatus_OK,
    ResponseStatus_TIMEOUT,
    ResponseStatus_ANALYSIS_FAILED,
    ResponseStatus_PARTIAL
  };
  return values;
}

inline const char * const *EnumNamesResponseStatus() {
  static const char * const names[5] = {
    "OK",
    "TIMEOUT",
    "ANALYSIS_FAILED",
    "PARTIAL",
    nullptr
  };
  return names;
}

inline const char *EnumNameResponseStatus(ResponseStatus e) {
  if (::flatbuffers::IsOutRange(e, ResponseStatus_OK, ResponseStatus_PARTIAL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesResponseStatus()[index];
}

enum DataTypeKind : int8_t {
  DataTypeKind_VOID = 0,
  DataTypeKind_BOOL = 1,
  DataTypeKind_INT = 2,
  DataTypeKind_UINT = 3,
  DataTypeKind_FLOAT = 4,
  DataTypeKind_POINTER = 5,
  DataTypeKind_ARRAY = 6,
  DataTypeKind_STRUCT = 7,
  DataTypeKind_UNION = 8,
  DataTypeKind_ENUM = 9,
  DataTypeKind_FUNCTION = 10,
  DataTypeKind_MIN = DataTypeKind_VOID,
  DataTypeKind_MAX = DataTypeKind_FUNCTION
};

inline const DataTypeKind (&EnumValuesDataTypeKind())[11] {
  static const DataTypeKind values[] = {
    DataTypeKind_VOID,
    DataTypeKind_BOOL,
    DataTypeKind_INT,
    DataTypeKind_UINT,
    DataTypeKind_FLOAT,
    DataTypeKind_POINTER,
    DataTypeKind_ARRAY,
    DataTypeKind_STRUCT,
    DataTypeKind_UNION,
    DataTypeKind_ENUM,
    DataTypeKind_FUNCTION
  };
  return values;
}

inline const char * const *EnumNamesDataTypeKind() {
  static const char * const names[12] = {
    "VOID",
    "BOOL",
    "INT",
    "UINT",
    "FLOAT",
    "POINTER",
    "ARRAY",
    "STRUCT",
    "UNION",
    "ENUM",
    "FUNCTION",
    nullptr
  };
  return names;
}

inline const char *EnumNameDataTypeKind(DataTypeKind e) {
  if (::flatbuffers::IsOutRange(e, DataTypeKind_VOID, DataTypeKind_FUNCTION)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDataTypeKind()[index];
}

enum StorageKind : int8_t {
  StorageKind_REGISTER = 0,
  StorageKind_STACK = 1,
  StorageKind_MEMORY = 2,
  StorageKind_HASH = 3,
  StorageKind_MIN = StorageKind_REGISTER,
  StorageKind_MAX = StorageKind_HASH
};

inline const StorageKind (&EnumValuesStorageKind())[4] {
  static const StorageKind values[] = {
    StorageKind_REGISTER,
    StorageKind_STACK,
    StorageKind_MEMORY,
    StorageKind_HASH
  };
  return values;
}

inline const char * const *EnumNamesStorageKind() {
  static const char * const names[5] = {
    "REGISTER",
    "STACK",
    "MEMORY",
    "HASH",
    nullptr
  };
  return names;
}

inline const char *EnumNameStorageKind(StorageKind e) {
  if (::flatbuffers::IsOutRange(e, StorageKind_REGISTER, StorageKind_HASH)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStorageKind()[index];
}

enum Severity : int8_t {
  Severity_INFO = 0,
  Severity_WARN = 1,
  Severity_ERROR = 2,
  Severity_MIN = Severity_INFO,
  Severity_MAX = Severity_ERROR
};

inline const Severity (&EnumValuesSeverity())[3] {
  static const Severity values[] = {
    Severity_INFO,
    Severity_WARN,
    Severity_ERROR
  };
  return values;
}

inline const char * const *EnumNamesSeverity() {
  static const char * const names[4] = {
    "INFO",
    "WARN",
    "ERROR",
    nullptr
  };
  return names;
}

inline const char *EnumNameSeverity(Severity e) {
  if (::flatbuffers::IsOutRange(e, Severity_INFO, Severity_ERROR)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSeverity()[index];
}

struct DataType FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DataTypeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_SIZE = 6,
    VT_KIND = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t size() const {
    return GetField<uint32_t>(VT_SIZE, 0);
  }
  ghidra::ipc::DataTypeKind kind() const {
    return static_cast<ghidra::ipc::DataTypeKind>(GetField<int8_t>(VT_KIND, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_SIZE, 4) &&
           VerifyField<int8_t>(verifier, VT_KIND, 1) &&
           verifier.EndTable();
  }
};

struct DataTypeBuilder {
  typedef DataType Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(DataType::VT_NAME, name);
  }
  void add_size(uint32_t size) {
    fbb_.AddElement<uint32_t>(DataType::VT_SIZE, size, 0);
  }
  void add_kind(ghidra::ipc::DataTypeKind kind) {
    fbb_.AddElement<int8_t>(DataType::VT_KIND, static_cast<int8_t>(kind), 0);
  }
  explicit DataTypeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DataType> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DataType>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DataType> CreateDataType(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint32_t size = 0,
    ghidra::ipc::DataTypeKind kind = ghidra::ipc::DataTypeKind_VOID) {
  DataTypeBuilder builder_(_fbb);
  builder_.add_size(size);
  builder_.add_name(name);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DataType> CreateDataTypeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    uint32_t size = 0,
    ghidra::ipc::DataTypeKind kind = ghidra::ipc::DataTypeKind_VOID) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return ghidra::ipc::CreateDataType(
      _fbb,
      name__,
      size,
      kind);
}

struct Storage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StorageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KIND = 4,
    VT_ADDRESS = 6,
    VT_SPACE = 8
  };
  ghidra::ipc::StorageKind kind() const {
    return static_cast<ghidra::ipc::StorageKind>(GetField<int8_t>(VT_KIND, 0));
  }
  uint64_t address() const {
    return GetField<uint64_t>(VT_ADDRESS, 0);
  }
  uint8_t space() const {
    return GetField<uint8_t>(VT_SPACE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_KIND, 1) &&
           VerifyField<uint64_t>(verifier, VT_ADDRESS, 8) &&
           VerifyField<uint8_t>(verifier, VT_SPACE, 1) &&
           verifier.EndTable();
  }
};

struct StorageBuilder {
  typedef Storage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_kind(ghidra::ipc::StorageKind kind) {
    fbb_.AddElement<int8_t>(Storage::VT_KIND, static_cast<int8_t>(kind), 0);
  }
  void add_address(uint64_t address) {
    fbb_.AddElement<uint64_t>(Storage::VT_ADDRESS, address, 0);
  }
  void add_space(uint8_t space) {
    fbb_.AddElement<uint8_t>(Storage::VT_SPACE, space, 0);
  }
  explicit StorageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Storage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Storage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Storage> CreateStorage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ghidra::ipc::StorageKind kind = ghidra::ipc::StorageKind_REGISTER,
    uint64_t address = 0,
    uint8_t space = 0) {
  StorageBuilder builder_(_fbb);
  builder_.add_address(address);
  builder_.add_space(space);
  builder_.add_kind(kind);
  return builder_.Finish();
}

struct Varnode FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VarnodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ADDRESS_SPACE = 4,
    VT_OFFSET = 6,
    VT_SIZE = 8
  };
  uint8_t address_space() const {
    return GetField<uint8_t>(VT_ADDRESS_SPACE, 0);
  }
  uint64_t offset() const {
    return GetField<uint64_t>(VT_OFFSET, 0);
  }
  uint32_t size() const {
    return GetField<uint32_t>(VT_SIZE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_ADDRESS_SPACE, 1) &&
           VerifyField<uint64_t>(verifier, VT_OFFSET, 8) &&
           VerifyField<uint32_t>(verifier, VT_SIZE, 4) &&
           verifier.EndTable();
  }
};

struct VarnodeBuilder {
  typedef Varnode Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_address_space(uint8_t address_space) {
    fbb_.AddElement<uint8_t>(Varnode::VT_ADDRESS_SPACE, address_space, 0);
  }
  void add_offset(uint64_t offset) {
    fbb_.AddElement<uint64_t>(Varnode::VT_OFFSET, offset, 0);
  }
  void add_size(uint32_t size) {
    fbb_.AddElement<uint32_t>(Varnode::VT_SIZE, size, 0);
  }
  explicit VarnodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Varnode> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Varnode>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Varnode> CreateVarnode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t address_space = 0,
    uint64_t offset = 0,
    uint32_t size = 0) {
  VarnodeBuilder builder_(_fbb);
  builder_.add_offset(offset);
  builder_.add_size(size);
  builder_.add_address_space(address_space);
  return builder_.Finish();
}

struct HighSymbol FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HighSymbolBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_TYPE = 6,
    VT_STORAGE = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ghidra::ipc::DataType *type() const {
    return GetPointer<const ghidra::ipc::DataType *>(VT_TYPE);
  }
  const ghidra::ipc::Storage *storage() const {
    return GetPointer<const ghidra::ipc::Storage *>(VT_STORAGE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyTable(type()) &&
           VerifyOffset(verifier, VT_STORAGE) &&
           verifier.VerifyTable(storage()) &&
           verifier.EndTable();
  }
};

struct HighSymbolBuilder {
  typedef HighSymbol Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(HighSymbol::VT_NAME, name);
  }
  void add_type(::flatbuffers::Offset<ghidra::ipc::DataType> type) {
    fbb_.AddOffset(HighSymbol::VT_TYPE, type);
  }
  void add_storage(::flatbuffers::Offset<ghidra::ipc::Storage> storage) {
    fbb_.AddOffset(HighSymbol::VT_STORAGE, storage);
  }
  explicit HighSymbolBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HighSymbol> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HighSymbol>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HighSymbol> CreateHighSymbol(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<ghidra::ipc::DataType> type = 0,
    ::flatbuffers::Offset<ghidra::ipc::Storage> storage = 0) {
  HighSymbolBuilder builder_(_fbb);
  builder_.add_storage(storage);
  builder_.add_type(type);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<HighSymbol> CreateHighSymbolDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    ::flatbuffers::Offset<ghidra::ipc::DataType> type = 0,
    ::flatbuffers::Offset<ghidra::ipc::Storage> storage = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return ghidra::ipc::CreateHighSymbol(
      _fbb,
      name__,
      type,
      storage);
}

struct HighFunction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HighFunctionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_RETURN_TYPE = 6,
    VT_PARAMETERS = 8,
    VT_LOCALS = 10
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ghidra::ipc::DataType *return_type() const {
    return GetPointer<const ghidra::ipc::DataType *>(VT_RETURN_TYPE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::HighSymbol>> *parameters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::HighSymbol>> *>(VT_PARAMETERS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::HighSymbol>> *locals() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::HighSymbol>> *>(VT_LOCALS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_RETURN_TYPE) &&
           verifier.VerifyTable(return_type()) &&
           VerifyOffset(verifier, VT_PARAMETERS) &&
           verifier.VerifyVector(parameters()) &&
           verifier.VerifyVectorOfTables(parameters()) &&
           VerifyOffset(verifier, VT_LOCALS) &&
           verifier.VerifyVector(locals()) &&
           verifier.VerifyVectorOfTables(locals()) &&
           verifier.EndTable();
  }
};

struct HighFunctionBuilder {
  typedef HighFunction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(HighFunction::VT_NAME, name);
  }
  void add_return_type(::flatbuffers::Offset<ghidra::ipc::DataType> return_type) {
    fbb_.AddOffset(HighFunction::VT_RETURN_TYPE, return_type);
  }
  void add_parameters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::HighSymbol>>> parameters) {
    fbb_.AddOffset(HighFunction::VT_PARAMETERS, parameters);
  }
  void add_locals(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::HighSymbol>>> locals) {
    fbb_.AddOffset(HighFunction::VT_LOCALS, locals);
  }
  explicit HighFunctionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HighFunction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HighFunction>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HighFunction> CreateHighFunction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<ghidra::ipc::DataType> return_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::HighSymbol>>> parameters = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::HighSymbol>>> locals = 0) {
  HighFunctionBuilder builder_(_fbb);
  builder_.add_locals(locals);
  builder_.add_parameters(parameters);
  builder_.add_return_type(return_type);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<HighFunction> CreateHighFunctionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    ::flatbuffers::Offset<ghidra::ipc::DataType> return_type = 0,
    const std::vector<::flatbuffers::Offset<ghidra::ipc::HighSymbol>> *parameters = nullptr,
    const std::vector<::flatbuffers::Offset<ghidra::ipc::HighSymbol>> *locals = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto parameters__ = parameters ? _fbb.CreateVector<::flatbuffers::Offset<ghidra::ipc::HighSymbol>>(*parameters) : 0;
  auto locals__ = locals ? _fbb.CreateVector<::flatbuffers::Offset<ghidra::ipc::HighSymbol>>(*locals) : 0;
  return ghidra::ipc::CreateHighFunction(
      _fbb,
      name__,
      return_type,
      parameters__,
      locals__);
}

struct PcodeOp FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PcodeOpBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OPCODE = 4,
    VT_OUTPUT = 6,
    VT_INPUTS = 8,
    VT_SEQUENCE_NUMBER = 10
  };
  uint16_t opcode() const {
    return GetField<uint16_t>(VT_OPCODE, 0);
  }
  const ghidra::ipc::Varnode *output() const {
    return GetPointer<const ghidra::ipc::Varnode *>(VT_OUTPUT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::Varnode>> *inputs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::Varnode>> *>(VT_INPUTS);
  }
  uint32_t sequence_number() const {
    return GetField<uint32_t>(VT_SEQUENCE_NUMBER, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_OPCODE, 2) &&
           VerifyOffset(verifier, VT_OUTPUT) &&
           verifier.VerifyTable(output()) &&
           VerifyOffset(verifier, VT_INPUTS) &&
           verifier.VerifyVector(inputs()) &&
           verifier.VerifyVectorOfTables(inputs()) &&
           VerifyField<uint32_t>(verifier, VT_SEQUENCE_NUMBER, 4) &&
           verifier.EndTable();
  }
};

struct PcodeOpBuilder {
  typedef PcodeOp Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_opcode(uint16_t opcode) {
    fbb_.AddElement<uint16_t>(PcodeOp::VT_OPCODE, opcode, 0);
  }
  void add_output(::flatbuffers::Offset<ghidra::ipc::Varnode> output) {
    fbb_.AddOffset(PcodeOp::VT_OUTPUT, output);
  }
  void add_inputs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::Varnode>>> inputs) {
    fbb_.AddOffset(PcodeOp::VT_INPUTS, inputs);
  }
  void add_sequence_number(uint32_t sequence_number) {
    fbb_.AddElement<uint32_t>(PcodeOp::VT_SEQUENCE_NUMBER, sequence_number, 0);
  }
  explicit PcodeOpBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PcodeOp> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PcodeOp>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PcodeOp> CreatePcodeOp(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t opcode = 0,
    ::flatbuffers::Offset<ghidra::ipc::Varnode> output = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::Varnode>>> inputs = 0,
    uint32_t sequence_number = 0) {
  PcodeOpBuilder builder_(_fbb);
  builder_.add_sequence_number(sequence_number);
  builder_.add_inputs(inputs);
  builder_.add_output(output);
  builder_.add_opcode(opcode);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PcodeOp> CreatePcodeOpDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t opcode = 0,
    ::flatbuffers::Offset<ghidra::ipc::Varnode> output = 0,
    const std::vector<::flatbuffers::Offset<ghidra::ipc::Varnode>> *inputs = nullptr,
    uint32_t sequence_number = 0) {
  auto inputs__ = inputs ? _fbb.CreateVector<::flatbuffers::Offset<ghidra::ipc::Varnode>>(*inputs) : 0;
  return ghidra::ipc::CreatePcodeOp(
      _fbb,
      opcode,
      output,
      inputs__,
      sequence_number);
}

struct Diagnostic FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DiagnosticBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEVERITY = 4,
    VT_MESSAGE = 6,
    VT_PCODE_SEQ = 8
  };
  ghidra::ipc::Severity severity() const {
    return static_cast<ghidra::ipc::Severity>(GetField<int8_t>(VT_SEVERITY, 0));
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  uint32_t pcode_seq() const {
    return GetField<uint32_t>(VT_PCODE_SEQ, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_SEVERITY, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyField<uint32_t>(verifier, VT_PCODE_SEQ, 4) &&
           verifier.EndTable();
  }
};

struct DiagnosticBuilder {
  typedef Diagnostic Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_severity(ghidra::ipc::Severity severity) {
    fbb_.AddElement<int8_t>(Diagnostic::VT_SEVERITY, static_cast<int8_t>(severity), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(Diagnostic::VT_MESSAGE, message);
  }
  void add_pcode_seq(uint32_t pcode_seq) {
    fbb_.AddElement<uint32_t>(Diagnostic::VT_PCODE_SEQ, pcode_seq, 0);
  }
  explicit DiagnosticBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Diagnostic> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Diagnostic>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Diagnostic> CreateDiagnostic(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ghidra::ipc::Severity severity = ghidra::ipc::Severity_INFO,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    uint32_t pcode_seq = 0) {
  DiagnosticBuilder builder_(_fbb);
  builder_.add_pcode_seq(pcode_seq);
  builder_.add_message(message);
  builder_.add_severity(severity);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Diagnostic> CreateDiagnosticDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ghidra::ipc::Severity severity = ghidra::ipc::Severity_INFO,
    const char *message = nullptr,
    uint32_t pcode_seq = 0) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return ghidra::ipc::CreateDiagnostic(
      _fbb,
      severity,
      message__,
      pcode_seq);
}

struct RegisterProgramRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RegisterProgramRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROCESSOR_SPEC = 4,
    VT_COMPILER_SPEC = 6,
    VT_TRANSLATE_SPEC = 8,
    VT_CORE_TYPES_SPEC = 10
  };
  const ::flatbuffers::String *processor_spec() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROCESSOR_SPEC);
  }
  const ::flatbuffers::String *compiler_spec() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COMPILER_SPEC);
  }
  const ::flatbuffers::String *translate_spec() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRANSLATE_SPEC);
  }
  const ::flatbuffers::String *core_types_spec() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CORE_TYPES_SPEC);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROCESSOR_SPEC) &&
           verifier.VerifyString(processor_spec()) &&
           VerifyOffset(verifier, VT_COMPILER_SPEC) &&
           verifier.VerifyString(compiler_spec()) &&
           VerifyOffset(verifier, VT_TRANSLATE_SPEC) &&
           verifier.VerifyString(translate_spec()) &&
           VerifyOffset(verifier, VT_CORE_TYPES_SPEC) &&
           verifier.VerifyString(core_types_spec()) &&
           verifier.EndTable();
  }
};

struct RegisterProgramRequestBuilder {
  typedef RegisterProgramRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_processor_spec(::flatbuffers::Offset<::flatbuffers::String> processor_spec) {
    fbb_.AddOffset(RegisterProgramRequest::VT_PROCESSOR_SPEC, processor_spec);
  }
  void add_compiler_spec(::flatbuffers::Offset<::flatbuffers::String> compiler_spec) {
    fbb_.AddOffset(RegisterProgramRequest::VT_COMPILER_SPEC, compiler_spec);
  }
  void add_translate_spec(::flatbuffers::Offset<::flatbuffers::String> translate_spec) {
    fbb_.AddOffset(RegisterProgramRequest::VT_TRANSLATE_SPEC, translate_spec);
  }
  void add_core_types_spec(::flatbuffers::Offset<::flatbuffers::String> core_types_spec) {
    fbb_.AddOffset(RegisterProgramRequest::VT_CORE_TYPES_SPEC, core_types_spec);
  }
  explicit RegisterProgramRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RegisterProgramRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RegisterProgramRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RegisterProgramRequest> CreateRegisterProgramRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> processor_spec = 0,
    ::flatbuffers::Offset<::flatbuffers::String> compiler_spec = 0,
    ::flatbuffers::Offset<::flatbuffers::String> translate_spec = 0,
    ::flatbuffers::Offset<::flatbuffers::String> core_types_spec = 0) {
  RegisterProgramRequestBuilder builder_(_fbb);
  builder_.add_core_types_spec(core_types_spec);
  builder_.add_translate_spec(translate_spec);
  builder_.add_compiler_spec(compiler_spec);
  builder_.add_processor_spec(processor_spec);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RegisterProgramRequest> CreateRegisterProgramRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *processor_spec = nullptr,
    const char *compiler_spec = nullptr,
    const char *translate_spec = nullptr,
    const char *core_types_spec = nullptr) {
  auto processor_spec__ = processor_spec ? _fbb.CreateString(processor_spec) : 0;
  auto compiler_spec__ = compiler_spec ? _fbb.CreateString(compiler_spec) : 0;
  auto translate_spec__ = translate_spec ? _fbb.CreateString(translate_spec) : 0;
  auto core_types_spec__ = core_types_spec ? _fbb.CreateString(core_types_spec) : 0;
  return ghidra::ipc::CreateRegisterProgramRequest(
      _fbb,
      processor_spec__,
      compiler_spec__,
      translate_spec__,
      core_types_spec__);
}

struct RegisterProgramResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RegisterProgramResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROGRAM_ID = 4
  };
  const ::flatbuffers::String *program_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROGRAM_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROGRAM_ID) &&
           verifier.VerifyString(program_id()) &&
           verifier.EndTable();
  }
};

struct RegisterProgramResponseBuilder {
  typedef RegisterProgramResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_program_id(::flatbuffers::Offset<::flatbuffers::String> program_id) {
    fbb_.AddOffset(RegisterProgramResponse::VT_PROGRAM_ID, program_id);
  }
  explicit RegisterProgramResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RegisterProgramResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RegisterProgramResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RegisterProgramResponse> CreateRegisterProgramResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> program_id = 0) {
  RegisterProgramResponseBuilder builder_(_fbb);
  builder_.add_program_id(program_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RegisterProgramResponse> CreateRegisterProgramResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *program_id = nullptr) {
  auto program_id__ = program_id ? _fbb.CreateString(program_id) : 0;
  return ghidra::ipc::CreateRegisterProgramResponse(
      _fbb,
      program_id__);
}

struct DeregisterProgramRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeregisterProgramRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROGRAM_ID = 4
  };
  const ::flatbuffers::String *program_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROGRAM_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROGRAM_ID) &&
           verifier.VerifyString(program_id()) &&
           verifier.EndTable();
  }
};

struct DeregisterProgramRequestBuilder {
  typedef DeregisterProgramRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_program_id(::flatbuffers::Offset<::flatbuffers::String> program_id) {
    fbb_.AddOffset(DeregisterProgramRequest::VT_PROGRAM_ID, program_id);
  }
  explicit DeregisterProgramRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeregisterProgramRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeregisterProgramRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DeregisterProgramRequest> CreateDeregisterProgramRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> program_id = 0) {
  DeregisterProgramRequestBuilder builder_(_fbb);
  builder_.add_program_id(program_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DeregisterProgramRequest> CreateDeregisterProgramRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *program_id = nullptr) {
  auto program_id__ = program_id ? _fbb.CreateString(program_id) : 0;
  return ghidra::ipc::CreateDeregisterProgramRequest(
      _fbb,
      program_id__);
}

struct DeregisterProgramResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeregisterProgramResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_META_COMMAND = 4
  };
  int32_t meta_command() const {
    return GetField<int32_t>(VT_META_COMMAND, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_META_COMMAND, 4) &&
           verifier.EndTable();
  }
};

struct DeregisterProgramResponseBuilder {
  typedef DeregisterProgramResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_meta_command(int32_t meta_command) {
    fbb_.AddElement<int32_t>(DeregisterProgramResponse::VT_META_COMMAND, meta_command, 0);
  }
  explicit DeregisterProgramResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeregisterProgramResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeregisterProgramResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DeregisterProgramResponse> CreateDeregisterProgramResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t meta_command = 0) {
  DeregisterProgramResponseBuilder builder_(_fbb);
  builder_.add_meta_command(meta_command);
  return builder_.Finish();
}

struct FlushNativeRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FlushNativeRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROGRAM_ID = 4
  };
  const ::flatbuffers::String *program_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROGRAM_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROGRAM_ID) &&
           verifier.VerifyString(program_id()) &&
           verifier.EndTable();
  }
};

struct FlushNativeRequestBuilder {
  typedef FlushNativeRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_program_id(::flatbuffers::Offset<::flatbuffers::String> program_id) {
    fbb_.AddOffset(FlushNativeRequest::VT_PROGRAM_ID, program_id);
  }
  explicit FlushNativeRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FlushNativeRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FlushNativeRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FlushNativeRequest> CreateFlushNativeRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> program_id = 0) {
  FlushNativeRequestBuilder builder_(_fbb);
  builder_.add_program_id(program_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FlushNativeRequest> CreateFlushNativeRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *program_id = nullptr) {
  auto program_id__ = program_id ? _fbb.CreateString(program_id) : 0;
  return ghidra::ipc::CreateFlushNativeRequest(
      _fbb,
      program_id__);
}

struct FlushNativeResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FlushNativeResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULT = 4
  };
  int32_t result() const {
    return GetField<int32_t>(VT_RESULT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_RESULT, 4) &&
           verifier.EndTable();
  }
};

struct FlushNativeResponseBuilder {
  typedef FlushNativeResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_result(int32_t result) {
    fbb_.AddElement<int32_t>(FlushNativeResponse::VT_RESULT, result, 0);
  }
  explicit FlushNativeResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FlushNativeResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FlushNativeResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FlushNativeResponse> CreateFlushNativeResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t result = 0) {
  FlushNativeResponseBuilder builder_(_fbb);
  builder_.add_result(result);
  return builder_.Finish();
}

struct DecompileFunctionRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DecompileFunctionRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROGRAM_ID = 4,
    VT_FUNCTION_ADDRESS = 6,
    VT_TIMEOUT_MS = 8,
    VT_FLAGS = 10
  };
  const ::flatbuffers::String *program_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROGRAM_ID);
  }
  uint64_t function_address() const {
    return GetField<uint64_t>(VT_FUNCTION_ADDRESS, 0);
  }
  uint32_t timeout_ms() const {
    return GetField<uint32_t>(VT_TIMEOUT_MS, 30000);
  }
  uint32_t flags() const {
    return GetField<uint32_t>(VT_FLAGS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROGRAM_ID) &&
           verifier.VerifyString(program_id()) &&
           VerifyField<uint64_t>(verifier, VT_FUNCTION_ADDRESS, 8) &&
           VerifyField<uint32_t>(verifier, VT_TIMEOUT_MS, 4) &&
           VerifyField<uint32_t>(verifier, VT_FLAGS, 4) &&
           verifier.EndTable();
  }
};

struct DecompileFunctionRequestBuilder {
  typedef DecompileFunctionRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_program_id(::flatbuffers::Offset<::flatbuffers::String> program_id) {
    fbb_.AddOffset(DecompileFunctionRequest::VT_PROGRAM_ID, program_id);
  }
  void add_function_address(uint64_t function_address) {
    fbb_.AddElement<uint64_t>(DecompileFunctionRequest::VT_FUNCTION_ADDRESS, function_address, 0);
  }
  void add_timeout_ms(uint32_t timeout_ms) {
    fbb_.AddElement<uint32_t>(DecompileFunctionRequest::VT_TIMEOUT_MS, timeout_ms, 30000);
  }
  void add_flags(uint32_t flags) {
    fbb_.AddElement<uint32_t>(DecompileFunctionRequest::VT_FLAGS, flags, 0);
  }
  explicit DecompileFunctionRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DecompileFunctionRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DecompileFunctionRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DecompileFunctionRequest> CreateDecompileFunctionRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> program_id = 0,
    uint64_t function_address = 0,
    uint32_t timeout_ms = 30000,
    uint32_t flags = 0) {
  DecompileFunctionRequestBuilder builder_(_fbb);
  builder_.add_function_address(function_address);
  builder_.add_flags(flags);
  builder_.add_timeout_ms(timeout_ms);
  builder_.add_program_id(program_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DecompileFunctionRequest> CreateDecompileFunctionRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *program_id = nullptr,
    uint64_t function_address = 0,
    uint32_t timeout_ms = 30000,
    uint32_t flags = 0) {
  auto program_id__ = program_id ? _fbb.CreateString(program_id) : 0;
  return ghidra::ipc::CreateDecompileFunctionRequest(
      _fbb,
      program_id__,
      function_address,
      timeout_ms,
      flags);
}

struct DecompileFunctionResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DecompileFunctionResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATUS = 4,
    VT_PCODE = 6,
    VT_HIGH_FUNCTION = 8,
    VT_DIAGNOSTICS = 10
  };
  ghidra::ipc::ResponseStatus status() const {
    return static_cast<ghidra::ipc::ResponseStatus>(GetField<int8_t>(VT_STATUS, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::PcodeOp>> *pcode() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::PcodeOp>> *>(VT_PCODE);
  }
  const ghidra::ipc::HighFunction *high_function() const {
    return GetPointer<const ghidra::ipc::HighFunction *>(VT_HIGH_FUNCTION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::Diagnostic>> *diagnostics() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::Diagnostic>> *>(VT_DIAGNOSTICS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_STATUS, 1) &&
           VerifyOffset(verifier, VT_PCODE) &&
           verifier.VerifyVector(pcode()) &&
           verifier.VerifyVectorOfTables(pcode()) &&
           VerifyOffset(verifier, VT_HIGH_FUNCTION) &&
           verifier.VerifyTable(high_function()) &&
           VerifyOffset(verifier, VT_DIAGNOSTICS) &&
           verifier.VerifyVector(diagnostics()) &&
           verifier.VerifyVectorOfTables(diagnostics()) &&
           verifier.EndTable();
  }
};

struct DecompileFunctionResponseBuilder {
  typedef DecompileFunctionResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_status(ghidra::ipc::ResponseStatus status) {
    fbb_.AddElement<int8_t>(DecompileFunctionResponse::VT_STATUS, static_cast<int8_t>(status), 0);
  }
  void add_pcode(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::PcodeOp>>> pcode) {
    fbb_.AddOffset(DecompileFunctionResponse::VT_PCODE, pcode);
  }
  void add_high_function(::flatbuffers::Offset<ghidra::ipc::HighFunction> high_function) {
    fbb_.AddOffset(DecompileFunctionResponse::VT_HIGH_FUNCTION, high_function);
  }
  void add_diagnostics(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::Diagnostic>>> diagnostics) {
    fbb_.AddOffset(DecompileFunctionResponse::VT_DIAGNOSTICS, diagnostics);
  }
  explicit DecompileFunctionResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DecompileFunctionResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DecompileFunctionResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DecompileFunctionResponse> CreateDecompileFunctionResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ghidra::ipc::ResponseStatus status = ghidra::ipc::ResponseStatus_OK,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::PcodeOp>>> pcode = 0,
    ::flatbuffers::Offset<ghidra::ipc::HighFunction> high_function = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ghidra::ipc::Diagnostic>>> diagnostics = 0) {
  DecompileFunctionResponseBuilder builder_(_fbb);
  builder_.add_diagnostics(diagnostics);
  builder_.add_high_function(high_function);
  builder_.add_pcode(pcode);
  builder_.add_status(status);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DecompileFunctionResponse> CreateDecompileFunctionResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ghidra::ipc::ResponseStatus status = ghidra::ipc::ResponseStatus_OK,
    const std::vector<::flatbuffers::Offset<ghidra::ipc::PcodeOp>> *pcode = nullptr,
    ::flatbuffers::Offset<ghidra::ipc::HighFunction> high_function = 0,
    const std::vector<::flatbuffers::Offset<ghidra::ipc::Diagnostic>> *diagnostics = nullptr) {
  auto pcode__ = pcode ? _fbb.CreateVector<::flatbuffers::Offset<ghidra::ipc::PcodeOp>>(*pcode) : 0;
  auto diagnostics__ = diagnostics ? _fbb.CreateVector<::flatbuffers::Offset<ghidra::ipc::Diagnostic>>(*diagnostics) : 0;
  return ghidra::ipc::CreateDecompileFunctionResponse(
      _fbb,
      status,
      pcode__,
      high_function,
      diagnostics__);
}

struct StructureGraphRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StructureGraphRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROGRAM_ID = 4,
    VT_CONTROL_FLOW = 6
  };
  const ::flatbuffers::String *program_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROGRAM_ID);
  }
  const ::flatbuffers::String *control_flow() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONTROL_FLOW);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROGRAM_ID) &&
           verifier.VerifyString(program_id()) &&
           VerifyOffset(verifier, VT_CONTROL_FLOW) &&
           verifier.VerifyString(control_flow()) &&
           verifier.EndTable();
  }
};

struct StructureGraphRequestBuilder {
  typedef StructureGraphRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_program_id(::flatbuffers::Offset<::flatbuffers::String> program_id) {
    fbb_.AddOffset(StructureGraphRequest::VT_PROGRAM_ID, program_id);
  }
  void add_control_flow(::flatbuffers::Offset<::flatbuffers::String> control_flow) {
    fbb_.AddOffset(StructureGraphRequest::VT_CONTROL_FLOW, control_flow);
  }
  explicit StructureGraphRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StructureGraphRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StructureGraphRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StructureGraphRequest> CreateStructureGraphRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> program_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> control_flow = 0) {
  StructureGraphRequestBuilder builder_(_fbb);
  builder_.add_control_flow(control_flow);
  builder_.add_program_id(program_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StructureGraphRequest> CreateStructureGraphRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *program_id = nullptr,
    const char *control_flow = nullptr) {
  auto program_id__ = program_id ? _fbb.CreateString(program_id) : 0;
  auto control_flow__ = control_flow ? _fbb.CreateString(control_flow) : 0;
  return ghidra::ipc::CreateStructureGraphRequest(
      _fbb,
      program_id__,
      control_flow__);
}

struct StructureGraphResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StructureGraphResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STRUCTURED = 4
  };
  const ::flatbuffers::String *structured() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STRUCTURED);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_STRUCTURED) &&
           verifier.VerifyString(structured()) &&
           verifier.EndTable();
  }
};

struct StructureGraphResponseBuilder {
  typedef StructureGraphResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_structured(::flatbuffers::Offset<::flatbuffers::String> structured) {
    fbb_.AddOffset(StructureGraphResponse::VT_STRUCTURED, structured);
  }
  explicit StructureGraphResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StructureGraphResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StructureGraphResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StructureGraphResponse> CreateStructureGraphResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> structured = 0) {
  StructureGraphResponseBuilder builder_(_fbb);
  builder_.add_structured(structured);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StructureGraphResponse> CreateStructureGraphResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *structured = nullptr) {
  auto structured__ = structured ? _fbb.CreateString(structured) : 0;
  return ghidra::ipc::CreateStructureGraphResponse(
      _fbb,
      structured__);
}

struct SetActionRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetActionRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROGRAM_ID = 4,
    VT_ROOT_ACTION = 6,
    VT_PRINT_CONFIG = 8
  };
  const ::flatbuffers::String *program_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROGRAM_ID);
  }
  const ::flatbuffers::String *root_action() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ROOT_ACTION);
  }
  const ::flatbuffers::String *print_config() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PRINT_CONFIG);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROGRAM_ID) &&
           verifier.VerifyString(program_id()) &&
           VerifyOffset(verifier, VT_ROOT_ACTION) &&
           verifier.VerifyString(root_action()) &&
           VerifyOffset(verifier, VT_PRINT_CONFIG) &&
           verifier.VerifyString(print_config()) &&
           verifier.EndTable();
  }
};

struct SetActionRequestBuilder {
  typedef SetActionRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_program_id(::flatbuffers::Offset<::flatbuffers::String> program_id) {
    fbb_.AddOffset(SetActionRequest::VT_PROGRAM_ID, program_id);
  }
  void add_root_action(::flatbuffers::Offset<::flatbuffers::String> root_action) {
    fbb_.AddOffset(SetActionRequest::VT_ROOT_ACTION, root_action);
  }
  void add_print_config(::flatbuffers::Offset<::flatbuffers::String> print_config) {
    fbb_.AddOffset(SetActionRequest::VT_PRINT_CONFIG, print_config);
  }
  explicit SetActionRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetActionRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetActionRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetActionRequest> CreateSetActionRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> program_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> root_action = 0,
    ::flatbuffers::Offset<::flatbuffers::String> print_config = 0) {
  SetActionRequestBuilder builder_(_fbb);
  builder_.add_print_config(print_config);
  builder_.add_root_action(root_action);
  builder_.add_program_id(program_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetActionRequest> CreateSetActionRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *program_id = nullptr,
    const char *root_action = nullptr,
    const char *print_config = nullptr) {
  auto program_id__ = program_id ? _fbb.CreateString(program_id) : 0;
  auto root_action__ = root_action ? _fbb.CreateString(root_action) : 0;
  auto print_config__ = print_config ? _fbb.CreateString(print_config) : 0;
  return ghidra::ipc::CreateSetActionRequest(
      _fbb,
      program_id__,
      root_action__,
      print_config__);
}

struct SetActionResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetActionResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUCCESS = 4
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           verifier.EndTable();
  }
};

struct SetActionResponseBuilder {
  typedef SetActionResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(SetActionResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  explicit SetActionResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetActionResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetActionResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetActionResponse> CreateSetActionResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false) {
  SetActionResponseBuilder builder_(_fbb);
  builder_.add_success(success);
  return builder_.Finish();
}

struct SetOptionsRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetOptionsRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROGRAM_ID = 4,
    VT_OPTIONS = 6
  };
  const ::flatbuffers::String *program_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROGRAM_ID);
  }
  const ::flatbuffers::String *options() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OPTIONS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROGRAM_ID) &&
           verifier.VerifyString(program_id()) &&
           VerifyOffset(verifier, VT_OPTIONS) &&
           verifier.VerifyString(options()) &&
           verifier.EndTable();
  }
};

struct SetOptionsRequestBuilder {
  typedef SetOptionsRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_program_id(::flatbuffers::Offset<::flatbuffers::String> program_id) {
    fbb_.AddOffset(SetOptionsRequest::VT_PROGRAM_ID, program_id);
  }
  void add_options(::flatbuffers::Offset<::flatbuffers::String> options) {
    fbb_.AddOffset(SetOptionsRequest::VT_OPTIONS, options);
  }
  explicit SetOptionsRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetOptionsRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetOptionsRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetOptionsRequest> CreateSetOptionsRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> program_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> options = 0) {
  SetOptionsRequestBuilder builder_(_fbb);
  builder_.add_options(options);
  builder_.add_program_id(program_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetOptionsRequest> CreateSetOptionsRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *program_id = nullptr,
    const char *options = nullptr) {
  auto program_id__ = program_id ? _fbb.CreateString(program_id) : 0;
  auto options__ = options ? _fbb.CreateString(options) : 0;
  return ghidra::ipc::CreateSetOptionsRequest(
      _fbb,
      program_id__,
      options__);
}

struct SetOptionsResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetOptionsResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUCCESS = 4
  };
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           verifier.EndTable();
  }
};

struct SetOptionsResponseBuilder {
  typedef SetOptionsResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(SetOptionsResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  explicit SetOptionsResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetOptionsResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetOptionsResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetOptionsResponse> CreateSetOptionsResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool success = false) {
  SetOptionsResponseBuilder builder_(_fbb);
  builder_.add_success(success);
  return builder_.Finish();
}

inline const ghidra::ipc::DecompileFunctionRequest *GetDecompileFunctionRequest(const void *buf) {
  return ::flatbuffers::GetRoot<ghidra::ipc::DecompileFunctionRequest>(buf);
}

inline const ghidra::ipc::DecompileFunctionRequest *GetSizePrefixedDecompileFunctionRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ghidra::ipc::DecompileFunctionRequest>(buf);
}

template <bool B = false>
inline bool VerifyDecompileFunctionRequestBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<ghidra::ipc::DecompileFunctionRequest>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedDecompileFunctionRequestBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<ghidra::ipc::DecompileFunctionRequest>(nullptr);
}

inline void FinishDecompileFunctionRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ghidra::ipc::DecompileFunctionRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDecompileFunctionRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ghidra::ipc::DecompileFunctionRequest> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ipc
}  // namespace ghidra

#endif  // FLATBUFFERS_GENERATED_DECOMPILE_GHIDRA_IPC_H_
