// gayhydra-dropper: reverse-engineering training sample.
//
// Behavior: enumerates mounted filesystems from /proc/mounts, filters out
// pseudo-filesystems and read-only mounts, and drops a calling-card file
// (1337.txt) at the root of each remaining mount.
//
// Intended as a Ghidra/GayHydra training target. Strings are XOR-obfuscated
// with a single-byte key so students have something to deobfuscate beyond
// `strings(1)`. The control flow is intentionally straightforward.
//
// SAFE TO RUN AS A NON-ROOT USER: writes will fail on mounts the invoking
// user can't write to, and the program continues past errors rather than
// stopping. As a non-root user on a typical Linux box, this usually only
// writes to $HOME's filesystem and /tmp.
//
// DO NOT RUN AS ROOT unless you're in a throwaway VM. Do not ship the
// compiled binary anywhere it could be mistaken for a real implant.

package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const xorKey byte = 0x5A

// deobfuscate decodes a XOR-obfuscated string. The obfuscated blobs below
// were produced with the same key; see scripts/obfuscate.go for the encoder.
func deobfuscate(b []byte) string {
	out := make([]byte, len(b))
	for i, c := range b {
		out[i] = c ^ xorKey
	}
	return string(out)
}

// Obfuscated string table. Decoded values:
//   sFilename     = "1337.txt"
//   sPayload      = "File generated by GayHydra.\n"
//   sMountsPath   = "/proc/mounts"
//   sSkipPrefixes = "proc sys dev run tmpfs devtmpfs cgroup cgroup2 " +
//                   "pstore bpf tracefs debugfs securityfs configfs " +
//                   "fusectl mqueue hugetlbfs autofs binfmt_misc " +
//                   "rpc_pipefs nsfs overlay squashfs"
var (
	sFilename = []byte{
		0x6B, 0x69, 0x69, 0x6D, 0x74, 0x2E, 0x22, 0x2E,
	}
	sPayload = []byte{
		0x1C, 0x33, 0x36, 0x3F, 0x7A, 0x3D, 0x3F, 0x34, 0x3F, 0x28, 0x3B, 0x2E, 0x3F, 0x3E, 0x7A,
		0x38, 0x23, 0x7A, 0x1D, 0x3B, 0x23, 0x12, 0x23, 0x3E, 0x28, 0x3B, 0x74, 0x50,
	}
	sMountsPath = []byte{
		0x75, 0x2A, 0x28, 0x35, 0x39, 0x75, 0x37, 0x35, 0x2F, 0x34, 0x2E, 0x29,
	}
	sSkipPrefixes = []byte{
		0x2A, 0x28, 0x35, 0x39, 0x7A, 0x29, 0x23, 0x29, 0x7A, 0x3E, 0x3F, 0x2C, 0x7A, 0x28, 0x2F,
		0x34, 0x7A, 0x2E, 0x37, 0x2A, 0x3C, 0x29, 0x7A, 0x3E, 0x3F, 0x2C, 0x2E, 0x37, 0x2A, 0x3C,
		0x29, 0x7A, 0x39, 0x3D, 0x28, 0x35, 0x2F, 0x2A, 0x7A, 0x39, 0x3D, 0x28, 0x35, 0x2F, 0x2A,
		0x68, 0x7A, 0x2A, 0x29, 0x2E, 0x35, 0x28, 0x3F, 0x7A, 0x38, 0x2A, 0x3C, 0x7A, 0x2E, 0x28,
		0x3B, 0x39, 0x3F, 0x3C, 0x29, 0x7A, 0x3E, 0x3F, 0x38, 0x2F, 0x3D, 0x3C, 0x29, 0x7A, 0x29,
		0x3F, 0x39, 0x2F, 0x28, 0x33, 0x2E, 0x23, 0x3C, 0x29, 0x7A, 0x39, 0x35, 0x34, 0x3C, 0x33,
		0x3D, 0x3C, 0x29, 0x7A, 0x3C, 0x2F, 0x29, 0x3F, 0x39, 0x2E, 0x36, 0x7A, 0x37, 0x2B, 0x2F,
		0x3F, 0x2F, 0x3F, 0x7A, 0x32, 0x2F, 0x3D, 0x3F, 0x2E, 0x36, 0x38, 0x3C, 0x29, 0x7A, 0x3B,
		0x2F, 0x2E, 0x35, 0x3C, 0x29, 0x7A, 0x38, 0x33, 0x34, 0x3C, 0x37, 0x2E, 0x05, 0x37, 0x33,
		0x29, 0x39, 0x7A, 0x28, 0x2A, 0x39, 0x05, 0x2A, 0x33, 0x2A, 0x3F, 0x3C, 0x29, 0x7A, 0x34,
		0x29, 0x3C, 0x29, 0x7A, 0x35, 0x2C, 0x3F, 0x28, 0x36, 0x3B, 0x23, 0x7A, 0x29, 0x2B, 0x2F,
		0x3B, 0x29, 0x32, 0x3C, 0x29,
	}
)

// mountEntry mirrors the relevant columns of /proc/mounts:
//   device mountpoint fstype options ...
type mountEntry struct {
	device, mountpoint, fstype, options string
}

func parseMounts(path string) ([]mountEntry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var entries []mountEntry
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) < 4 {
			continue
		}
		entries = append(entries, mountEntry{
			device:     fields[0],
			mountpoint: fields[1],
			fstype:     fields[2],
			options:    fields[3],
		})
	}
	return entries, scanner.Err()
}

func isSkippable(fstype string, skip map[string]bool) bool {
	return skip[fstype]
}

func isReadOnly(options string) bool {
	for _, opt := range strings.Split(options, ",") {
		if opt == "ro" {
			return true
		}
	}
	return false
}

func dropCallingCard(mountpoint, filename, payload string) error {
	target := filepath.Join(mountpoint, filename)
	return os.WriteFile(target, []byte(payload), 0o644)
}

func main() {
	filename := deobfuscate(sFilename)
	payload := deobfuscate(sPayload)
	mountsPath := deobfuscate(sMountsPath)

	skip := map[string]bool{}
	for _, t := range strings.Fields(deobfuscate(sSkipPrefixes)) {
		skip[t] = true
	}

	entries, err := parseMounts(mountsPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse mounts: %v\n", err)
		os.Exit(1)
	}

	written, skipped, failed := 0, 0, 0
	for _, e := range entries {
		if isSkippable(e.fstype, skip) || isReadOnly(e.options) {
			skipped++
			continue
		}
		if err := dropCallingCard(e.mountpoint, filename, payload); err != nil {
			failed++
			continue
		}
		written++
		fmt.Printf("dropped: %s\n", filepath.Join(e.mountpoint, filename))
	}

	fmt.Printf("\nsummary: %d written, %d skipped, %d failed\n", written, skipped, failed)
}
