#!/usr/bin/env bash
# Sprint 15 (meta-review 2026-06-11), Tier 1 item 2: inbound upstream-drift
# measurement. Computes how far the fork has drifted from NSA/ghidra master
# and writes docs/upstream-tracking/drift-report.md.
#
# The give-back tracking (pr-issue-matches.md, give-back-candidates.md) is
# all *outbound*; this is the missing *inbound* half — the data a merge
# cadence decision needs. The dry-run is `git merge-tree --write-tree`
# (worktree-safe, no index/working-tree mutation), so this script is safe
# to run anywhere, including a dirty checkout.
#
# Usage: scripts/upstream-drift.sh
#   (adds an `upstream` remote pointing at NSA/ghidra if missing)

set -euo pipefail

UPSTREAM_URL=https://github.com/NationalSecurityAgency/ghidra.git
REPORT=docs/upstream-tracking/drift-report.md

cd "$(git rev-parse --show-toplevel)"

if ! git remote get-url upstream >/dev/null 2>&1; then
  git remote add upstream "$UPSTREAM_URL"
fi
git fetch --quiet upstream master --no-tags

BASE=$(git merge-base HEAD upstream/master)
BASE_DATE=$(git show -s --format=%cs "$BASE")
UPSTREAM_HEAD=$(git rev-parse --short upstream/master)
BEHIND=$(git rev-list --count HEAD..upstream/master)
AHEAD=$(git rev-list --count upstream/master..HEAD)

# Conflict *candidates*: files touched on both sides since the merge-base.
BOTH_TOUCHED=$(comm -12 \
  <(git diff --name-only "$BASE" HEAD | sort) \
  <(git diff --name-only "$BASE" upstream/master | sort))
BOTH_COUNT=$(printf '%s' "$BOTH_TOUCHED" | grep -c . || true)

# Actual conflicts: a worktree-safe dry-run merge. merge-tree exits 1 when
# the merge would conflict. The `--write-tree` output is: the tree OID
# (line 1), then the conflicted-file section (one path per line with
# `--name-only`), then a BLANK LINE, then informational messages
# ("Auto-merging …", "CONFLICT …"). Take ONLY the conflicted-file section
# (line 2 up to the first blank line) — an earlier version counted every
# non-blank line after line 1, which wrongly included the dozens of
# "Auto-merging" info lines and badly overcounted (74 reported vs 14 real).
set +e
MERGE_OUT=$(git merge-tree --write-tree --name-only HEAD upstream/master)
MERGE_STATUS=$?
set -e
if [ "$MERGE_STATUS" -eq 0 ]; then
  CONFLICTS=""
else
  CONFLICTS=$(printf '%s\n' "$MERGE_OUT" | awk 'NR==1{next} /^$/{exit} {print}')
fi
CONFLICT_COUNT=$(printf '%s' "$CONFLICTS" | grep -c . || true)

{
  echo "# Upstream drift report"
  echo
  echo "Inbound drift vs [NSA/ghidra](https://github.com/NationalSecurityAgency/ghidra)"
  echo "master. Regenerated by \`scripts/upstream-drift.sh\` (weekly via"
  echo "\`.github/workflows/upstream-drift.yml\`). The outbound half lives in"
  echo "[give-back-candidates.md](give-back-candidates.md) /"
  echo "[pr-issue-matches.md](pr-issue-matches.md)."
  echo
  echo "| Metric | Value |"
  echo "|---|---|"
  echo "| Merge base | \`${BASE:0:12}\` ($BASE_DATE) |"
  echo "| Upstream head | \`$UPSTREAM_HEAD\` |"
  echo "| Commits behind upstream | **$BEHIND** |"
  echo "| Commits ahead (fork-only) | $AHEAD |"
  echo "| Both-touched files (conflict candidates) | $BOTH_COUNT |"
  echo "| Dry-run merge conflicts (\`git merge-tree\`) | **$CONFLICT_COUNT** |"
  echo
  echo "## Files a merge would conflict on today"
  echo
  if [ -z "$CONFLICTS" ]; then
    echo "_None — a merge of upstream/master would apply cleanly._"
  else
    printf '%s\n' "$CONFLICTS" | sed 's/^/- `/; s/$/`/'
  fi
  echo
  echo "## Both-touched files (changed on both sides since the merge base)"
  echo
  if [ -z "$BOTH_TOUCHED" ]; then
    echo "_None._"
  else
    printf '%s\n' "$BOTH_TOUCHED" | sed 's/^/- `/; s/$/`/'
  fi
} > "$REPORT"

echo "Wrote $REPORT"
echo "behind=$BEHIND ahead=$AHEAD both_touched=$BOTH_COUNT conflicts=$CONFLICT_COUNT"
