// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

@SuppressWarnings("unused")
public final class DataTypeKind {
  private DataTypeKind() { }
  public static final byte VOID = 0;
  public static final byte BOOL = 1;
  public static final byte INT = 2;
  public static final byte UINT = 3;
  public static final byte FLOAT = 4;
  public static final byte POINTER = 5;
  public static final byte ARRAY = 6;
  public static final byte STRUCT = 7;
  public static final byte UNION = 8;
  public static final byte ENUM = 9;
  public static final byte FUNCTION = 10;

  public static final String[] names = { "VOID", "BOOL", "INT", "UINT", "FLOAT", "POINTER", "ARRAY", "STRUCT", "UNION", "ENUM", "FUNCTION", };

  public static String name(int e) { return names[e]; }
}

