// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DecompileBudget extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static DecompileBudget getRootAsDecompileBudget(ByteBuffer _bb) { return getRootAsDecompileBudget(_bb, new DecompileBudget()); }
  public static DecompileBudget getRootAsDecompileBudget(ByteBuffer _bb, DecompileBudget obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DecompileBudget __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long wallClockMs() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 30000L; }
  public long wallClockHardMs() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 60000L; }
  public long rssMaxMb() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 4096L; }
  public long pcodeOpLimit() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 1000000L; }
  public long iterationLimitPerPass() { int o = __offset(12); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 100L; }

  public static int createDecompileBudget(FlatBufferBuilder builder,
      long wallClockMs,
      long wallClockHardMs,
      long rssMaxMb,
      long pcodeOpLimit,
      long iterationLimitPerPass) {
    builder.startTable(5);
    DecompileBudget.addIterationLimitPerPass(builder, iterationLimitPerPass);
    DecompileBudget.addPcodeOpLimit(builder, pcodeOpLimit);
    DecompileBudget.addRssMaxMb(builder, rssMaxMb);
    DecompileBudget.addWallClockHardMs(builder, wallClockHardMs);
    DecompileBudget.addWallClockMs(builder, wallClockMs);
    return DecompileBudget.endDecompileBudget(builder);
  }

  public static void startDecompileBudget(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addWallClockMs(FlatBufferBuilder builder, long wallClockMs) { builder.addInt(0, (int) wallClockMs, (int) 30000L); }
  public static void addWallClockHardMs(FlatBufferBuilder builder, long wallClockHardMs) { builder.addInt(1, (int) wallClockHardMs, (int) 60000L); }
  public static void addRssMaxMb(FlatBufferBuilder builder, long rssMaxMb) { builder.addInt(2, (int) rssMaxMb, (int) 4096L); }
  public static void addPcodeOpLimit(FlatBufferBuilder builder, long pcodeOpLimit) { builder.addInt(3, (int) pcodeOpLimit, (int) 1000000L); }
  public static void addIterationLimitPerPass(FlatBufferBuilder builder, long iterationLimitPerPass) { builder.addInt(4, (int) iterationLimitPerPass, (int) 100L); }
  public static int endDecompileBudget(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DecompileBudget get(int j) { return get(new DecompileBudget(), j); }
    public DecompileBudget get(DecompileBudget obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

