// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DecompileFunctionResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static DecompileFunctionResponse getRootAsDecompileFunctionResponse(ByteBuffer _bb) { return getRootAsDecompileFunctionResponse(_bb, new DecompileFunctionResponse()); }
  public static DecompileFunctionResponse getRootAsDecompileFunctionResponse(ByteBuffer _bb, DecompileFunctionResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DecompileFunctionResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte status() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public ghidra.ipc.PcodeOp pcode(int j) { return pcode(new ghidra.ipc.PcodeOp(), j); }
  public ghidra.ipc.PcodeOp pcode(ghidra.ipc.PcodeOp obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int pcodeLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ghidra.ipc.PcodeOp.Vector pcodeVector() { return pcodeVector(new ghidra.ipc.PcodeOp.Vector()); }
  public ghidra.ipc.PcodeOp.Vector pcodeVector(ghidra.ipc.PcodeOp.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public ghidra.ipc.HighFunction highFunction() { return highFunction(new ghidra.ipc.HighFunction()); }
  public ghidra.ipc.HighFunction highFunction(ghidra.ipc.HighFunction obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public ghidra.ipc.Diagnostic diagnostics(int j) { return diagnostics(new ghidra.ipc.Diagnostic(), j); }
  public ghidra.ipc.Diagnostic diagnostics(ghidra.ipc.Diagnostic obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int diagnosticsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public ghidra.ipc.Diagnostic.Vector diagnosticsVector() { return diagnosticsVector(new ghidra.ipc.Diagnostic.Vector()); }
  public ghidra.ipc.Diagnostic.Vector diagnosticsVector(ghidra.ipc.Diagnostic.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createDecompileFunctionResponse(FlatBufferBuilder builder,
      byte status,
      int pcodeOffset,
      int highFunctionOffset,
      int diagnosticsOffset) {
    builder.startTable(4);
    DecompileFunctionResponse.addDiagnostics(builder, diagnosticsOffset);
    DecompileFunctionResponse.addHighFunction(builder, highFunctionOffset);
    DecompileFunctionResponse.addPcode(builder, pcodeOffset);
    DecompileFunctionResponse.addStatus(builder, status);
    return DecompileFunctionResponse.endDecompileFunctionResponse(builder);
  }

  public static void startDecompileFunctionResponse(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addStatus(FlatBufferBuilder builder, byte status) { builder.addByte(0, status, 0); }
  public static void addPcode(FlatBufferBuilder builder, int pcodeOffset) { builder.addOffset(1, pcodeOffset, 0); }
  public static int createPcodeVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPcodeVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addHighFunction(FlatBufferBuilder builder, int highFunctionOffset) { builder.addOffset(2, highFunctionOffset, 0); }
  public static void addDiagnostics(FlatBufferBuilder builder, int diagnosticsOffset) { builder.addOffset(3, diagnosticsOffset, 0); }
  public static int createDiagnosticsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDiagnosticsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endDecompileFunctionResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DecompileFunctionResponse get(int j) { return get(new DecompileFunctionResponse(), j); }
    public DecompileFunctionResponse get(DecompileFunctionResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

