// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DecompileFunctionRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static DecompileFunctionRequest getRootAsDecompileFunctionRequest(ByteBuffer _bb) { return getRootAsDecompileFunctionRequest(_bb, new DecompileFunctionRequest()); }
  public static DecompileFunctionRequest getRootAsDecompileFunctionRequest(ByteBuffer _bb, DecompileFunctionRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DecompileFunctionRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String programId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer programIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer programIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public long functionAddress() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long timeoutMs() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 30000L; }
  public long flags() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public ghidra.ipc.DecompileBudget budget() { return budget(new ghidra.ipc.DecompileBudget()); }
  public ghidra.ipc.DecompileBudget budget(ghidra.ipc.DecompileBudget obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createDecompileFunctionRequest(FlatBufferBuilder builder,
      int programIdOffset,
      long functionAddress,
      long timeoutMs,
      long flags,
      int budgetOffset) {
    builder.startTable(5);
    DecompileFunctionRequest.addFunctionAddress(builder, functionAddress);
    DecompileFunctionRequest.addBudget(builder, budgetOffset);
    DecompileFunctionRequest.addFlags(builder, flags);
    DecompileFunctionRequest.addTimeoutMs(builder, timeoutMs);
    DecompileFunctionRequest.addProgramId(builder, programIdOffset);
    return DecompileFunctionRequest.endDecompileFunctionRequest(builder);
  }

  public static void startDecompileFunctionRequest(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addProgramId(FlatBufferBuilder builder, int programIdOffset) { builder.addOffset(0, programIdOffset, 0); }
  public static void addFunctionAddress(FlatBufferBuilder builder, long functionAddress) { builder.addLong(1, functionAddress, 0L); }
  public static void addTimeoutMs(FlatBufferBuilder builder, long timeoutMs) { builder.addInt(2, (int) timeoutMs, (int) 30000L); }
  public static void addFlags(FlatBufferBuilder builder, long flags) { builder.addInt(3, (int) flags, (int) 0L); }
  public static void addBudget(FlatBufferBuilder builder, int budgetOffset) { builder.addOffset(4, budgetOffset, 0); }
  public static int endDecompileFunctionRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishDecompileFunctionRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedDecompileFunctionRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DecompileFunctionRequest get(int j) { return get(new DecompileFunctionRequest(), j); }
    public DecompileFunctionRequest get(DecompileFunctionRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

