// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DeregisterProgramResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static DeregisterProgramResponse getRootAsDeregisterProgramResponse(ByteBuffer _bb) { return getRootAsDeregisterProgramResponse(_bb, new DeregisterProgramResponse()); }
  public static DeregisterProgramResponse getRootAsDeregisterProgramResponse(ByteBuffer _bb, DeregisterProgramResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DeregisterProgramResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int metaCommand() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createDeregisterProgramResponse(FlatBufferBuilder builder,
      int metaCommand) {
    builder.startTable(1);
    DeregisterProgramResponse.addMetaCommand(builder, metaCommand);
    return DeregisterProgramResponse.endDeregisterProgramResponse(builder);
  }

  public static void startDeregisterProgramResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addMetaCommand(FlatBufferBuilder builder, int metaCommand) { builder.addInt(0, metaCommand, 0); }
  public static int endDeregisterProgramResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DeregisterProgramResponse get(int j) { return get(new DeregisterProgramResponse(), j); }
    public DeregisterProgramResponse get(DeregisterProgramResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

