// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Diagnostic extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Diagnostic getRootAsDiagnostic(ByteBuffer _bb) { return getRootAsDiagnostic(_bb, new Diagnostic()); }
  public static Diagnostic getRootAsDiagnostic(ByteBuffer _bb, Diagnostic obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Diagnostic __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte severity() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String message() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer messageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public long pcodeSeq() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createDiagnostic(FlatBufferBuilder builder,
      byte severity,
      int messageOffset,
      long pcodeSeq) {
    builder.startTable(3);
    Diagnostic.addPcodeSeq(builder, pcodeSeq);
    Diagnostic.addMessage(builder, messageOffset);
    Diagnostic.addSeverity(builder, severity);
    return Diagnostic.endDiagnostic(builder);
  }

  public static void startDiagnostic(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addSeverity(FlatBufferBuilder builder, byte severity) { builder.addByte(0, severity, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(1, messageOffset, 0); }
  public static void addPcodeSeq(FlatBufferBuilder builder, long pcodeSeq) { builder.addInt(2, (int) pcodeSeq, (int) 0L); }
  public static int endDiagnostic(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Diagnostic get(int j) { return get(new Diagnostic(), j); }
    public Diagnostic get(Diagnostic obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

