// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class HighSymbol extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static HighSymbol getRootAsHighSymbol(ByteBuffer _bb) { return getRootAsHighSymbol(_bb, new HighSymbol()); }
  public static HighSymbol getRootAsHighSymbol(ByteBuffer _bb, HighSymbol obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public HighSymbol __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public ghidra.ipc.DataType type() { return type(new ghidra.ipc.DataType()); }
  public ghidra.ipc.DataType type(ghidra.ipc.DataType obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public ghidra.ipc.Storage storage() { return storage(new ghidra.ipc.Storage()); }
  public ghidra.ipc.Storage storage(ghidra.ipc.Storage obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createHighSymbol(FlatBufferBuilder builder,
      int nameOffset,
      int typeOffset,
      int storageOffset) {
    builder.startTable(3);
    HighSymbol.addStorage(builder, storageOffset);
    HighSymbol.addType(builder, typeOffset);
    HighSymbol.addName(builder, nameOffset);
    return HighSymbol.endHighSymbol(builder);
  }

  public static void startHighSymbol(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int typeOffset) { builder.addOffset(1, typeOffset, 0); }
  public static void addStorage(FlatBufferBuilder builder, int storageOffset) { builder.addOffset(2, storageOffset, 0); }
  public static int endHighSymbol(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public HighSymbol get(int j) { return get(new HighSymbol(), j); }
    public HighSymbol get(HighSymbol obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

