// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PcodeOp extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static PcodeOp getRootAsPcodeOp(ByteBuffer _bb) { return getRootAsPcodeOp(_bb, new PcodeOp()); }
  public static PcodeOp getRootAsPcodeOp(ByteBuffer _bb, PcodeOp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PcodeOp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int opcode() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public ghidra.ipc.Varnode output() { return output(new ghidra.ipc.Varnode()); }
  public ghidra.ipc.Varnode output(ghidra.ipc.Varnode obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public ghidra.ipc.Varnode inputs(int j) { return inputs(new ghidra.ipc.Varnode(), j); }
  public ghidra.ipc.Varnode inputs(ghidra.ipc.Varnode obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int inputsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ghidra.ipc.Varnode.Vector inputsVector() { return inputsVector(new ghidra.ipc.Varnode.Vector()); }
  public ghidra.ipc.Varnode.Vector inputsVector(ghidra.ipc.Varnode.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public long sequenceNumber() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createPcodeOp(FlatBufferBuilder builder,
      int opcode,
      int outputOffset,
      int inputsOffset,
      long sequenceNumber) {
    builder.startTable(4);
    PcodeOp.addSequenceNumber(builder, sequenceNumber);
    PcodeOp.addInputs(builder, inputsOffset);
    PcodeOp.addOutput(builder, outputOffset);
    PcodeOp.addOpcode(builder, opcode);
    return PcodeOp.endPcodeOp(builder);
  }

  public static void startPcodeOp(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addOpcode(FlatBufferBuilder builder, int opcode) { builder.addShort(0, (short) opcode, (short) 0); }
  public static void addOutput(FlatBufferBuilder builder, int outputOffset) { builder.addOffset(1, outputOffset, 0); }
  public static void addInputs(FlatBufferBuilder builder, int inputsOffset) { builder.addOffset(2, inputsOffset, 0); }
  public static int createInputsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startInputsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addSequenceNumber(FlatBufferBuilder builder, long sequenceNumber) { builder.addInt(3, (int) sequenceNumber, (int) 0L); }
  public static int endPcodeOp(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PcodeOp get(int j) { return get(new PcodeOp(), j); }
    public PcodeOp get(PcodeOp obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

