// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class RegisterProgramRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static RegisterProgramRequest getRootAsRegisterProgramRequest(ByteBuffer _bb) { return getRootAsRegisterProgramRequest(_bb, new RegisterProgramRequest()); }
  public static RegisterProgramRequest getRootAsRegisterProgramRequest(ByteBuffer _bb, RegisterProgramRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RegisterProgramRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String processorSpec() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer processorSpecAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer processorSpecInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String compilerSpec() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer compilerSpecAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer compilerSpecInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String translateSpec() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer translateSpecAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer translateSpecInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String coreTypesSpec() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer coreTypesSpecAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer coreTypesSpecInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createRegisterProgramRequest(FlatBufferBuilder builder,
      int processorSpecOffset,
      int compilerSpecOffset,
      int translateSpecOffset,
      int coreTypesSpecOffset) {
    builder.startTable(4);
    RegisterProgramRequest.addCoreTypesSpec(builder, coreTypesSpecOffset);
    RegisterProgramRequest.addTranslateSpec(builder, translateSpecOffset);
    RegisterProgramRequest.addCompilerSpec(builder, compilerSpecOffset);
    RegisterProgramRequest.addProcessorSpec(builder, processorSpecOffset);
    return RegisterProgramRequest.endRegisterProgramRequest(builder);
  }

  public static void startRegisterProgramRequest(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addProcessorSpec(FlatBufferBuilder builder, int processorSpecOffset) { builder.addOffset(0, processorSpecOffset, 0); }
  public static void addCompilerSpec(FlatBufferBuilder builder, int compilerSpecOffset) { builder.addOffset(1, compilerSpecOffset, 0); }
  public static void addTranslateSpec(FlatBufferBuilder builder, int translateSpecOffset) { builder.addOffset(2, translateSpecOffset, 0); }
  public static void addCoreTypesSpec(FlatBufferBuilder builder, int coreTypesSpecOffset) { builder.addOffset(3, coreTypesSpecOffset, 0); }
  public static int endRegisterProgramRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RegisterProgramRequest get(int j) { return get(new RegisterProgramRequest(), j); }
    public RegisterProgramRequest get(RegisterProgramRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

