// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

@SuppressWarnings("unused")
public final class ResponseStatus {
  private ResponseStatus() { }
  public static final byte OK = 0;
  public static final byte TIMEOUT = 1;
  public static final byte ANALYSIS_FAILED = 2;
  public static final byte PARTIAL = 3;

  public static final String[] names = { "OK", "TIMEOUT", "ANALYSIS_FAILED", "PARTIAL", };

  public static String name(int e) { return names[e]; }
}

