// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SetActionRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static SetActionRequest getRootAsSetActionRequest(ByteBuffer _bb) { return getRootAsSetActionRequest(_bb, new SetActionRequest()); }
  public static SetActionRequest getRootAsSetActionRequest(ByteBuffer _bb, SetActionRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SetActionRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String programId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer programIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer programIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String rootAction() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer rootActionAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer rootActionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String printConfig() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer printConfigAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer printConfigInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createSetActionRequest(FlatBufferBuilder builder,
      int programIdOffset,
      int rootActionOffset,
      int printConfigOffset) {
    builder.startTable(3);
    SetActionRequest.addPrintConfig(builder, printConfigOffset);
    SetActionRequest.addRootAction(builder, rootActionOffset);
    SetActionRequest.addProgramId(builder, programIdOffset);
    return SetActionRequest.endSetActionRequest(builder);
  }

  public static void startSetActionRequest(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addProgramId(FlatBufferBuilder builder, int programIdOffset) { builder.addOffset(0, programIdOffset, 0); }
  public static void addRootAction(FlatBufferBuilder builder, int rootActionOffset) { builder.addOffset(1, rootActionOffset, 0); }
  public static void addPrintConfig(FlatBufferBuilder builder, int printConfigOffset) { builder.addOffset(2, printConfigOffset, 0); }
  public static int endSetActionRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SetActionRequest get(int j) { return get(new SetActionRequest(), j); }
    public SetActionRequest get(SetActionRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

