// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SetOptionsResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static SetOptionsResponse getRootAsSetOptionsResponse(ByteBuffer _bb) { return getRootAsSetOptionsResponse(_bb, new SetOptionsResponse()); }
  public static SetOptionsResponse getRootAsSetOptionsResponse(ByteBuffer _bb, SetOptionsResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SetOptionsResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean success() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createSetOptionsResponse(FlatBufferBuilder builder,
      boolean success) {
    builder.startTable(1);
    SetOptionsResponse.addSuccess(builder, success);
    return SetOptionsResponse.endSetOptionsResponse(builder);
  }

  public static void startSetOptionsResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addSuccess(FlatBufferBuilder builder, boolean success) { builder.addBoolean(0, success, false); }
  public static int endSetOptionsResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SetOptionsResponse get(int j) { return get(new SetOptionsResponse(), j); }
    public SetOptionsResponse get(SetOptionsResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

