// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SetOptionsRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static SetOptionsRequest getRootAsSetOptionsRequest(ByteBuffer _bb) { return getRootAsSetOptionsRequest(_bb, new SetOptionsRequest()); }
  public static SetOptionsRequest getRootAsSetOptionsRequest(ByteBuffer _bb, SetOptionsRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SetOptionsRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String programId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer programIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer programIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String options() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer optionsAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer optionsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createSetOptionsRequest(FlatBufferBuilder builder,
      int programIdOffset,
      int optionsOffset) {
    builder.startTable(2);
    SetOptionsRequest.addOptions(builder, optionsOffset);
    SetOptionsRequest.addProgramId(builder, programIdOffset);
    return SetOptionsRequest.endSetOptionsRequest(builder);
  }

  public static void startSetOptionsRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addProgramId(FlatBufferBuilder builder, int programIdOffset) { builder.addOffset(0, programIdOffset, 0); }
  public static void addOptions(FlatBufferBuilder builder, int optionsOffset) { builder.addOffset(1, optionsOffset, 0); }
  public static int endSetOptionsRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SetOptionsRequest get(int j) { return get(new SetOptionsRequest(), j); }
    public SetOptionsRequest get(SetOptionsRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

