// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

@SuppressWarnings("unused")
public final class Severity {
  private Severity() { }
  public static final byte INFO = 0;
  public static final byte WARN = 1;
  public static final byte ERROR = 2;

  public static final String[] names = { "INFO", "WARN", "ERROR", };

  public static String name(int e) { return names[e]; }
}

