// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Storage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Storage getRootAsStorage(ByteBuffer _bb) { return getRootAsStorage(_bb, new Storage()); }
  public static Storage getRootAsStorage(ByteBuffer _bb, Storage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Storage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte kind() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long address() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int space() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createStorage(FlatBufferBuilder builder,
      byte kind,
      long address,
      int space) {
    builder.startTable(3);
    Storage.addAddress(builder, address);
    Storage.addSpace(builder, space);
    Storage.addKind(builder, kind);
    return Storage.endStorage(builder);
  }

  public static void startStorage(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addKind(FlatBufferBuilder builder, byte kind) { builder.addByte(0, kind, 0); }
  public static void addAddress(FlatBufferBuilder builder, long address) { builder.addLong(1, address, 0L); }
  public static void addSpace(FlatBufferBuilder builder, int space) { builder.addByte(2, (byte) space, (byte) 0); }
  public static int endStorage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Storage get(int j) { return get(new Storage(), j); }
    public Storage get(Storage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

