// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

@SuppressWarnings("unused")
public final class StorageKind {
  private StorageKind() { }
  public static final byte REGISTER = 0;
  public static final byte STACK = 1;
  public static final byte MEMORY = 2;
  public static final byte HASH = 3;

  public static final String[] names = { "REGISTER", "STACK", "MEMORY", "HASH", };

  public static String name(int e) { return names[e]; }
}

