// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class StructureGraphResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static StructureGraphResponse getRootAsStructureGraphResponse(ByteBuffer _bb) { return getRootAsStructureGraphResponse(_bb, new StructureGraphResponse()); }
  public static StructureGraphResponse getRootAsStructureGraphResponse(ByteBuffer _bb, StructureGraphResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StructureGraphResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String structured() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer structuredAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer structuredInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createStructureGraphResponse(FlatBufferBuilder builder,
      int structuredOffset) {
    builder.startTable(1);
    StructureGraphResponse.addStructured(builder, structuredOffset);
    return StructureGraphResponse.endStructureGraphResponse(builder);
  }

  public static void startStructureGraphResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addStructured(FlatBufferBuilder builder, int structuredOffset) { builder.addOffset(0, structuredOffset, 0); }
  public static int endStructureGraphResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StructureGraphResponse get(int j) { return get(new StructureGraphResponse(), j); }
    public StructureGraphResponse get(StructureGraphResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

