// automatically generated by the FlatBuffers compiler, do not modify

package ghidra.ipc;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Varnode extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Varnode getRootAsVarnode(ByteBuffer _bb) { return getRootAsVarnode(_bb, new Varnode()); }
  public static Varnode getRootAsVarnode(ByteBuffer _bb, Varnode obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Varnode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int addressSpace() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public long offset() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long size() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createVarnode(FlatBufferBuilder builder,
      int addressSpace,
      long offset,
      long size) {
    builder.startTable(3);
    Varnode.addOffset(builder, offset);
    Varnode.addSize(builder, size);
    Varnode.addAddressSpace(builder, addressSpace);
    return Varnode.endVarnode(builder);
  }

  public static void startVarnode(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addAddressSpace(FlatBufferBuilder builder, int addressSpace) { builder.addByte(0, (byte) addressSpace, (byte) 0); }
  public static void addOffset(FlatBufferBuilder builder, long offset) { builder.addLong(1, offset, 0L); }
  public static void addSize(FlatBufferBuilder builder, long size) { builder.addInt(2, (int) size, (int) 0L); }
  public static int endVarnode(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Varnode get(int j) { return get(new Varnode(), j); }
    public Varnode get(Varnode obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

